"""add location and website

Revision ID: 010faa5b671f
Revises: b2b7582650e3
Create Date: 2021-12-11 18:01:52.785209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010faa5b671f'
down_revision = 'b2b7582650e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'website')
    op.drop_column('user', 'location')
    # ### end Alembic commands ###
