"""follower in bio

Revision ID: 8ca90cb44a34
Revises: 8bcb717390ac
Create Date: 2021-12-17 13:24:09.988513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca90cb44a34'
down_revision = '8bcb717390ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('follower_bio', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'follower_bio')
    # ### end Alembic commands ###
